import { useEffect, useRef, useState } from 'react';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import { ArrowDown, ArrowUpRight, Download, Github, Linkedin, Mail, Menu, X, Check, ShieldCheck, Database, BarChart3, Sparkles } from 'lucide-react';
import { projects, selected, contributions, type Project, type Category } from './data';

const NAV = [['About','#about'],['Expertise','#expertise'],['Projects','#projects'],['Experience','#experience'],['Contact','#contact']];
const ease = [0.25,0.1,0.25,1] as const;
function Fade({children, className='', delay=0}: {children:React.ReactNode;className?:string;delay?:number}) {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={reduce?false:{opacity:0,y:34}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.12}} transition={{duration:.75,delay,ease}}>{children}</motion.div>;
}
function ContactButton({children='Contact me',href='mailto:someshzanwar345@gmail.com'}:{children?:React.ReactNode;href?:string}) {
  return <a href={href} className="contact-pill">{children}<ArrowUpRight size={18} aria-hidden="true" /></a>;
}
function Nav() {
  const [open,setOpen]=useState(false);
  return <header className="site-nav"><a className="site-logo" href="#top" aria-label="Somesh Zanwar, home">SZ<span className="logo-dot">.</span></a><nav className={open?'nav-list nav-open':'nav-list'} aria-label="Primary navigation">{NAV.map(([label,href])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="nav-resume" href="/Somesh_Zanwar.pdf" download><Download size={16} aria-hidden="true"/> Resume</a><button className="menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?<X size={25}/>:<Menu size={25}/>}</button></header>;
}
function Hero() {
  const portrait=useRef<HTMLDivElement>(null);
  const reduce=useReducedMotion();
  function magnet(e:React.PointerEvent<HTMLDivElement>){if(reduce||e.pointerType!=='mouse'||!portrait.current)return;const r=portrait.current.getBoundingClientRect();portrait.current.style.setProperty('--mx',`${Math.max(-20,Math.min(20,(e.clientX-r.left-r.width/2)/12))}px`);portrait.current.style.setProperty('--my',`${Math.max(-20,Math.min(20,(e.clientY-r.top-r.height/2)/12))}px`)}
  function reset(){portrait.current?.style.setProperty('--mx','0px');portrait.current?.style.setProperty('--my','0px')}
  return <section className="hero" id="top" aria-labelledby="hero-title"><div className="hero-inner"><Fade className="hero-top"><span>Data. Systems. Intelligence.</span><span>Arlington, TX / 2026</span></Fade><div className="hero-title-wrap"><Fade delay={.15}><h1 id="hero-title" className="hero-title">Hi, I’m <span>Somesh</span></h1></Fade></div><Fade className="hero-bottom" delay={.35}><p>Building reliable data systems and useful AI, from first question to real decision.</p><ContactButton>Let's talk</ContactButton></Fade><motion.div className="hero-person" ref={portrait} onPointerMove={magnet} onPointerLeave={reset} initial={reduce?false:{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{duration:.9,delay:.55,ease}}><div className="portrait-glow"/><img src="/Somesh_Headshot.png" alt="Somesh Zanwar" fetchPriority="high"/></motion.div></div><a href="#about" className="scroll-cue">Scroll to explore <ArrowDown size={17} /></a></section>;
}
function RibbonCard({project}:{project:Project}) {
  return <div className={`ribbon-card ${project.accent}`}><span className="ribbon-card-top">{project.category}</span><span className="ribbon-glyph" aria-hidden="true">{project.category==='Analytics'?<BarChart3/>:project.category==='Data Engineering'?<Database/>:<Sparkles/>}</span><strong>{project.title}</strong><span className="ribbon-card-bottom">{project.stack.slice(0,2).join(' / ')}</span></div>;
}
function Marquee() {
  const ref=useRef<HTMLElement>(null); const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']}); const first=useTransform(scrollYProgress,[0,1],[-310,70]); const second=useTransform(scrollYProgress,[0,1],[-40,-430]); const reduce=useReducedMotion(); const rowA=projects.slice(0,7),rowB=projects.slice(7,14);
  return <section className="marquee" ref={ref} aria-label="Project highlights"><div className="marquee-row"><motion.div className="marquee-track" style={reduce?{}:{x:first}}>{rowA.map(p=><RibbonCard key={p.id} project={p}/>)}</motion.div></div><div className="marquee-row"><motion.div className="marquee-track" style={reduce?{}:{x:second}}>{rowB.map(p=><RibbonCard key={p.id} project={p}/>)}</motion.div></div></section>;
}
function RevealChar({char,index,total,progress}:{char:string;index:number;total:number;progress:ReturnType<typeof useScroll>['scrollYProgress']}) {
  const opacity=useTransform(progress,[index/total*.8,Math.min(1,index/total*.8+.15)],[.23,1]); return <motion.span style={{opacity}}>{char}</motion.span>;
}
function About() {
  const text="I’m a data science master’s student at UT Arlington, and I build analytics workflows, dependable data pipelines, and AI systems with validation and clear controls. I care about the point where a useful insight becomes a reliable decision.";
  const ref=useRef<HTMLParagraphElement>(null); const {scrollYProgress}=useScroll({target:ref,offset:['start 0.85','end 0.3']}); const reduce=useReducedMotion();
  return <section className="about section-dark" id="about"><div className="float-object float-one" aria-hidden="true"><Database/></div><div className="float-object float-two" aria-hidden="true"><Sparkles/></div><div className="float-object float-three" aria-hidden="true"><ShieldCheck/></div><div className="float-object float-four" aria-hidden="true"><BarChart3/></div><Fade><p className="eyebrow">01 / Get to know me</p><h2 className="section-title gradient-text">About me</h2></Fade><p className="about-copy" ref={ref}>{reduce?text:[...text].map((char,i)=><RevealChar key={i} char={char} index={i} total={text.length} progress={scrollYProgress}/>)}</p><Fade delay={.2}><ContactButton href="#experience">See my experience</ContactButton></Fade></section>;
}
const services=[
  ['Analytics & BI','SQL and Python analysis, KPI definitions, Power BI reporting, and clear stories for stakeholders.'],
  ['Data Engineering','PostgreSQL and dbt transformations, reusable models, validation, and data pipelines.'],
  ['Experimentation','Hypothesis tests, segment analysis, confidence intervals, and practical rollout decisions.'],
  ['Applied ML & AI','Model evaluation, explainability, API-backed applications, and agent execution controls.'],
  ['Governance & Reliability','Data quality checks, lineage, incident visibility, policy evidence, and auditable actions.']
];
function Expertise(){return <section className="expertise" id="expertise"><div className="section-container"><Fade><p className="eyebrow dark-eyebrow">02 / Areas of practice</p><h2 className="section-title">Expertise</h2></Fade><div className="service-list">{services.map(([name,description],i)=><Fade className="service-row" key={name} delay={i*.08}><span className="service-number">{String(i+1).padStart(2,'0')}</span><div><h3>{name}</h3><p>{description}</p></div><ArrowUpRight className="service-arrow" aria-hidden="true"/></Fade>)}</div></div></section>}
function ProjectVisual({project}:{project:Project}){
  const digits=project.id==='experimentation'?['50K','280K+','95%']:project.id==='datatrust'?['12','CI','SQL']:['21','RS256','API'];
  return <div className={`visual-grid ${project.accent}`} aria-hidden="true"><div className="visual-pane small-pane"><span className="visual-label">INSIGHT / 01</span><div className="visual-big">{digits[0]}</div><div className="visual-bars">{[48,72,56,88,67,95,80].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></div><div className="visual-pane small-pane"><span className="visual-label">SIGNAL / 02</span><div className="visual-big">{digits[1]}</div><div className="visual-dots">{Array.from({length:20},(_,i)=><i key={i} className={i%5===0?'lit':''}/>)}</div></div><div className="visual-pane large-pane"><span className="visual-label">SYSTEM STATUS / 03</span><div className="visual-orbit"><div className="orbit-center"><Check size={36}/></div><i/><i/><i/></div><div className="visual-footer"><span>VALIDATION COMPLETE</span><strong>{digits[2]}</strong></div></div></div>
}
function FeaturedCard({project,index,total}:{project:Project;index:number;total:number}){
  const ref=useRef<HTMLElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end start']}); const scale=useTransform(scrollYProgress,[0,1],[1,1-(total-1-index)*.03]);const reduce=useReducedMotion();
  return <article className="sticky-slot" ref={ref}><motion.div className="feature-card" style={reduce?{}:{scale,top:`${95+index*18}px`}}><div className="feature-top"><span className="feature-num">{String(index+1).padStart(2,'0')}</span><div><span className="feature-category">{project.category}</span><h3>{project.title}</h3></div><a className="outline-pill" href={project.demo||project.repo} target="_blank" rel="noopener noreferrer">{project.demo?'Live project':'View project'} <ArrowUpRight size={17}/></a></div><ProjectVisual project={project}/><div className="feature-summary"><p>{project.description}</p><span>{project.stack.join(' · ')}</span></div></motion.div></article>
}
function ProjectTile({project}:{project:Project}) {return <article className={`project-tile ${project.accent}`}><span className="tile-category">{project.category} <span>{project.status||'Built'}</span></span><h3>{project.title}</h3><p>{project.description}</p><div className="tile-tags">{project.stack.slice(0,3).map(s=><span key={s}>{s}</span>)}</div><div className="tile-links">{project.demo&&<a href={project.demo} target="_blank" rel="noopener noreferrer">Live demo <ArrowUpRight size={15}/></a>}{project.repo&&<a href={project.repo} target="_blank" rel="noopener noreferrer">GitHub <ArrowUpRight size={15}/></a>}{!project.repo&&<span>Private repository</span>}</div></article>}
function Projects(){const [filter,setFilter]=useState<'All'|Category>('All');const featured=selected.map(id=>projects.find(p=>p.id===id)!);return <section className="projects section-dark" id="projects"><div className="section-container"><Fade><p className="eyebrow">03 / Work in practice</p><h2 className="section-title gradient-text">Projects</h2><p className="section-lede">Systems for trustworthy data, practical analytics, and responsible AI.</p></Fade><div className="feature-stack">{featured.map((p,i)=><FeaturedCard key={p.id} project={p} index={i} total={featured.length}/>)}</div><div id="all-projects" className="all-projects"><Fade><p className="eyebrow">The complete index</p><h3>All projects <span>({projects.length})</span></h3></Fade><div className="filters" role="group" aria-label="Filter projects">{(['All','Analytics','Data Engineering','AI Engineering'] as const).map(cat=><button type="button" key={cat} className={filter===cat?'selected':''} aria-pressed={filter===cat} onClick={()=>setFilter(cat)}>{cat}</button>)}</div><div className="project-grid">{projects.filter(p=>filter==='All'||p.category===filter).map(p=><ProjectTile key={p.id} project={p}/>)}</div></div></div></section>}
function Experience(){return <section className="experience section-dark" id="experience"><div className="section-container"><Fade><p className="eyebrow">04 / Professional experience</p><h2 className="section-title gradient-text">Experience</h2></Fade><div className="experience-layout"><Fade><p className="experience-date">Sep 2022 — Sep 2024 <span>· Pune, India</span></p><h3>Junior Data Analyst</h3><p className="experience-company">IVS Software Solutions</p><p className="experience-description">Used SQL, Python, Excel, and Power BI to turn operational data into reusable reports and clearer decisions for three internal teams. Documented metric definitions, transformations, checks, and discrepancy resolutions.</p><a href="/Somesh_Zanwar.pdf" download className="outline-pill">Download resume <Download size={17}/></a></Fade><div className="metric-grid"><Fade><strong>80K–150K</strong><span>records analyzed per cycle</span></Fade><Fade delay={.08}><strong>30%</strong><span>improvement in reporting accuracy</span></Fade><Fade delay={.16}><strong>40%</strong><span>less data preparation time</span></Fade><Fade delay={.24}><strong>4–6 hrs</strong><span>saved per reporting cycle</span></Fade></div></div></div></section>}
function OpenSource(){return <section className="open-source section-dark" id="open-source"><div className="section-container"><Fade><p className="eyebrow">05 / Beyond my own projects</p><h2 className="section-title gradient-text">Open source</h2><p className="section-lede">Five merged pull requests to Microsoft’s Agent Governance Toolkit, plus AgentTrust and A2A/CTEF governance work.</p></Fade><div className="contribution-grid"><div className="contribution-main"><span className="contrib-kicker">Microsoft / Agent Governance Toolkit</span><h3>Five merged contributions</h3>{contributions.map(c=><a key={c.id} href={`https://github.com/microsoft/agent-governance-toolkit/pull/${c.id}`} target="_blank" rel="noopener noreferrer"><span>#{c.id}</span>{c.title}<ArrowUpRight size={15}/></a>)}</div><div className="contribution-side"><h3>More in the ecosystem</h3><p>AgentTrust: completed verifier, runtime, RAG scan state, identity, and security-evidence issues across repositories.</p><p>A2A / CTEF: proposed a data quality trust scheme with conformance vectors and governance guidance.</p><a href="https://github.com/SomeshZanwar" target="_blank" rel="noopener noreferrer">Explore GitHub <ArrowUpRight size={17}/></a></div></div></div></section>}
function Education(){return <section className="education section-dark"><div className="section-container"><Fade><p className="eyebrow">06 / Foundation</p><h2 className="section-title gradient-text">Education</h2></Fade><div className="education-grid"><div><span>2025 — 2026</span><h3>M.S. Data Science</h3><p>The University of Texas at Arlington</p><strong>GPA 3.67 / 4.00</strong></div><div><span>2020 — 2024</span><h3>B.E. Artificial Intelligence & Machine Learning</h3><p>Savitribai Phule Pune University</p><strong>GPA 8.2 / 10</strong></div></div></div></section>}
function Contact(){return <section className="contact section-dark" id="contact"><div className="section-container"><Fade><p className="eyebrow">07 / Your next teammate</p><h2 className="section-title gradient-text">Let's work<br/>together.</h2><p className="section-lede">Open to data analyst, data engineer, and AI engineer opportunities.</p><div className="contact-actions"><ContactButton>Email me</ContactButton><a href="/Somesh_Zanwar.pdf" download className="outline-pill">Download resume <Download size={17}/></a></div></Fade><footer><span>© {new Date().getFullYear()} Somesh Zanwar</span><div><a href="mailto:someshzanwar345@gmail.com" aria-label="Email"><Mail size={20}/></a><a href="https://www.linkedin.com/in/someshzanwar/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><Linkedin size={20}/></a><a href="https://github.com/SomeshZanwar" target="_blank" rel="noopener noreferrer" aria-label="GitHub"><Github size={20}/></a></div><a href="#top">Back to top ↑</a></footer></div></section>}
export default function App(){
  useEffect(() => {
    // Legacy page redirects retain their section hash before React mounts.
    if (location.hash) requestAnimationFrame(() =>
      document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView());
  }, []);
  return <><Nav/><main><Hero/><Marquee/><About/><Expertise/><Projects/><Experience/><OpenSource/><Education/><Contact/></main></>;
}
