export type Category = 'Analytics' | 'Data Engineering' | 'AI Engineering';
export type Project = { id: string; title: string; category: Category; description: string; stack: string[]; repo?: string; demo?: string; status?: string; accent: string };
const github = 'https://github.com/SomeshZanwar/';
export const projects: Project[] = [
  { id:'metrictrust', title:'MetricTrust Control Plane', category:'AI Engineering', description:'Evidence-bound execution control for analytics agents. Policy checks, short-lived signed permits, and 21 automated tests govern downstream actions.', stack:['Python','FastAPI','SQLAlchemy','pytest'], repo:github+'metrictrust-control-plane', demo:'https://metrictrust-control-plane.onrender.com/', accent:'violet' },
  { id:'uta-oit', title:'UTA OIT Intelligent IT Ticket Routing', category:'AI Engineering', description:'In-progress capstone with UTA’s Office of Information Technology, exploring ticket data preparation, text features, and model evaluation for service-team routing.', stack:['Python','Text analysis','Model evaluation'], status:'In progress · private repository', accent:'blue' },
  { id:'datatrust', title:'DataTrust OS', category:'Data Engineering', description:'Operational data-trust workflow with 12 automated quality checks, incident tracking, lineage, and CI validation.', stack:['Python','PostgreSQL','dbt','Streamlit'], repo:github+'Datatrust-OS', accent:'cyan' },
  { id:'experimentation', title:'Decision Intelligence Experimentation Platform', category:'Analytics', description:'An experiment workflow for 50,000 simulated users and 280,000+ events, with lift, confidence intervals, and segment-level rollout evidence.', stack:['PostgreSQL','dbt','Python'], repo:github+'Decision-Intelligence-Experimentation-Platform', demo:'https://experiment-decision-simulator.streamlit.app/', accent:'orange' },
  { id:'metric-decomposition', title:'Metric Decomposition Engine', category:'Analytics', description:'Investigates KPI movement across dimensions, ranks contributing segments, and generates stakeholder-ready reports using GitHub Archive data.', stack:['Python','PostgreSQL','Streamlit'], repo:github+'Metric-Decomposition-Engine', demo:'https://metric-change-investigator.streamlit.app/', accent:'blue' },
  { id:'ai-data-governance', title:'AI Data Governance Platform', category:'Data Engineering', description:'Monitors pipeline data quality, detects incidents, and makes validation failures visible for reporting and governance decisions.', stack:['PostgreSQL','dbt','Python','Power BI'], repo:github+'AI-Data-Governance-Platform', demo:'https://data-reliability-control-center.streamlit.app/', accent:'cyan' },
  { id:'agent-governance', title:'Data Quality-Aware Agent Governance', category:'AI Engineering', description:'Combines policy authorization with dataset quality signals to determine whether an AI agent can use data at the time of access.', stack:['Python','Microsoft AGT','Policy'], repo:github+'Data-Quality-Aware-Agent-Governance', demo:'https://agent-governance-simulator.streamlit.app/', accent:'violet' },
  { id:'aigov', title:'AIGov Control Tower', category:'AI Engineering', description:'Full-stack registry and oversight interface for AI systems, including evidence, risk triage, and policy controls.', stack:['FastAPI','PostgreSQL','React'], repo:github+'AIGov-Control-Tower', accent:'violet' },
  { id:'retail-inventory', title:'Retail Sales & Inventory Analytics', category:'Analytics', description:'Retail transaction analysis to surface revenue drivers, SKU priorities, and demand patterns for inventory decisions.', stack:['SQL','Python','Analytics'], repo:github+'Retail-Sales-Inventory-Analytics', accent:'orange' },
  { id:'retail-ops', title:'Retail Operations KPI & QA Dashboard', category:'Data Engineering', description:'Instacart analytics with PostgreSQL staging, a dimensional model, KPI queries, integrity checks, and a Power BI dashboard.', stack:['PostgreSQL','SQL','Power BI'], repo:github+'Retail-Ops-KPI-Dashboard', accent:'cyan' },
  { id:'churn', title:'Customer Churn Prediction & Explainability', category:'AI Engineering', description:'Compares churn models with stored test ROC-AUC of 0.843, then uses SHAP and LIME for interpretable retention insights.', stack:['Python','XGBoost','SHAP'], repo:github+'Customer-Churn-Prediction-Explainability', accent:'violet' },
  { id:'olympics', title:'Olympic Performance Dashboard', category:'Analytics', description:'Interactive exploration of historical Olympic athlete records, participation, medal trends, and country performance.', stack:['Python','pandas','Plotly'], repo:github+'Olympic-Performance-Dashboard', accent:'orange' },
  { id:'vit', title:'ViT Robustness Lab', category:'AI Engineering', description:'Collaborative application exploring vision-transformer attention, perturbed images, and adversarial robustness.', stack:['React','TypeScript','Gemini'], repo:github+'ViT-Robustness-Lab', status:'Collaborative project', accent:'blue' },
  { id:'pyredis', title:'PyRedis', category:'AI Engineering', description:'Redis-like network server handling multiple requests per connection and sequential clients.', stack:['Python','Networking','Protocols'], repo:github+'PyRedis', accent:'violet' }
];
export const selected = ['metrictrust', 'datatrust', 'experimentation'];
export const contributions = [
  { id:'1818', title:'Added a data quality-aware governance adopter entry' },
  { id:'2038', title:'Fixed Agent SRE tutorial API and Windows guidance' },
  { id:'2114', title:'Corrected AgentMesh quickstart scaffolding' },
  { id:'2224', title:'Added a data quality-aware governance example' },
  { id:'2278', title:'Added a dbt-backed DataQualityEvidence adapter' }
];
